version: '3.9'
services:
  nginx:
      build: .
      container_name: nginx
      restart: unless-stopped
      ports:
        - "80:80"
      logging:
        driver: "json-file"
        options:
          max-size: "50m"
          max-file: "5"
          tag: "{{.ImageName}}|{{.Name}}"
